version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  web:
    build: .
    restart: always
    volumes:
      - ./nuitinfo:/var/www
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: mongo
      MONGO_PASSWORD: password
      MONGO_USER: username
      JWT_SECRET: bJC2rlw0IW7XcsV5pWrFvcAK86y9JMD4L8JLB75BBmFJ00heK6yXtXMPDglcrZhl
      ### Email deliver
      # Supported services are available here: https://github.com/nodemailer/nodemailer-wellknown#supported-services
      ENV MAIL_SERVICE: custom
      ENV MAIL_ADDRESS: email@default.com
      ENV MAIL_PASSWORD: password
      ENV MAIL_HOST: smtp.default.com
      ENV MAIL_PORT: 777
      # 0 for false and 1 for true
      ENV MAIL_SECURE: 1
    depends_on:
      - adminer
      - mongo

volumes:
  database:
  nuitinfo: